"""Performance report generation (TXT and PDF)."""

import os
from datetime import datetime

from fpdf import FPDF

from paths import get_app_dir


def _build_report_text(stats, period="daily"):
    """Build report content as plain text."""
    now = datetime.now().strftime("%d-%m-%Y %I:%M %p")
    period_label = stats.get("period_label", "Daily")

    if not stats or stats.get("total_records", 0) == 0:
        return (
            f"SYSTEM PERFORMANCE REPORT\n"
            f"{'=' * 40}\n\n"
            f"Date: {now}\n"
            f"Period: {period_label}\n\n"
            f"No performance logs found for this period.\n"
            f"Save some logs first using the 'Save Log' button.\n"
        )

    return (
        f"SYSTEM PERFORMANCE REPORT\n"
        f"{'=' * 40}\n\n"
        f"Date: {now}\n"
        f"Period: {period_label}\n"
        f"Total Records: {stats['total_records']}\n\n"
        f"CPU STATISTICS\n"
        f"{'-' * 20}\n"
        f"Average CPU Usage : {stats['avg_cpu']:.1f}%\n"
        f"Highest CPU Usage : {stats['max_cpu']:.1f}%\n"
        f"Lowest CPU Usage  : {stats['min_cpu']:.1f}%\n\n"
        f"RAM STATISTICS\n"
        f"{'-' * 20}\n"
        f"Average RAM Usage : {stats['avg_ram']:.1f}%\n"
        f"Highest RAM Usage : {stats['max_ram']:.1f}%\n"
        f"Lowest RAM Usage  : {stats['min_ram']:.1f}%\n\n"
        f"DISK STATISTICS\n"
        f"{'-' * 20}\n"
        f"Average Disk Usage: {stats['avg_disk']:.1f}%\n"
        f"Highest Disk Usage: {stats['max_disk']:.1f}%\n"
        f"Lowest Disk Usage : {stats['min_disk']:.1f}%\n\n"
        f"{'=' * 40}\n"
        f"Generated by System Performance Analyser\n"
    )


def _reports_dir():
    return os.path.join(get_app_dir(), "reports")


def generate_txt_report(stats, output_dir=None):
    """Save report as a TXT file."""
    output_dir = output_dir or _reports_dir()
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filepath = os.path.join(output_dir, f"performance_report_{timestamp}.txt")

    content = _build_report_text(stats)
    with open(filepath, "w", encoding="utf-8") as file:
        file.write(content)

    return filepath, content


def generate_pdf_report(stats, output_dir=None):
    """Save report as a PDF file."""
    output_dir = output_dir or _reports_dir()
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filepath = os.path.join(output_dir, f"performance_report_{timestamp}.pdf")

    content = _build_report_text(stats)
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_font("Helvetica", size=11)

    for line in content.split("\n"):
        safe_line = line.encode("latin-1", errors="replace").decode("latin-1")
        pdf.multi_cell(0, 7, safe_line)

    pdf.output(filepath)
    return filepath, content
